[advisories]
ignore = [
    "RUSTSEC-2026-0194",
    "RUSTSEC-2026-0195",
    "RUSTSEC-2026-0192",
    "RUSTSEC-2024-0413",
    "RUSTSEC-2024-0416",
    "RUSTSEC-2024-0412",
    "RUSTSEC-2024-0418",
    "RUSTSEC-2024-0415",
    "RUSTSEC-2024-0420",
    "RUSTSEC-2024-0419",
    "RUSTSEC-2024-0370",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OpenSSL",
    "CC0-1.0",
    "0BSD",
    "BSL-1.0"
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
