name: Test

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

permissions:
  contents: read
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Test Suite
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          components: rustfmt, clippy

      - name: Setup sccache
        uses: mozilla-actions/sccache-action

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "crm-rust-shared-cache"
          cache-on-failure: true
          cache-targets: false

      - name: Run format check
        run: cargo fmt -- --check

      - name: Run clippy
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: cargo test --workspace --all-targets --all-features

      #- name: Build all models and binaries
        #run: cargo build --all-targets
